# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[profile.production]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
# eth-rpc-url = "https://eth-mainnet.g.alchemy.com/v2/"
optimizer-runs = 10_000_000

[profile.ci]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
# ffi = true
optimizer-runs = 10_000_000

[rpc_endpoints]
goerli = "https://ethereum-goerli.publicnode.com"
# See .env for mainnet network

[fmt]
line_length = 80